### PR TITLE
Refactor notifications

### PR DESCRIPTION
**Pull request by minacode**
This PR patches the simulator for [the notification refactoring](https://github.com/InfiniTimeOrg/InfiniTime/pull/1482).

### CODE REVIEW

**Review by NeroBurner — APPROVED** [review]

**Comment by NeroBurner** [comment]
for the time you could also update the infinitime submodule to your branch. This should work even without changing the submodule url. Just changing the checked in commit should be enough (I don't know why, but it seems to work like this on GitHub).

**Comment by minacode** [comment]
> Just changing the checked in commit should be enough

How can I do this? I haven't done this before and there are a lot of different explanations online that seem to do different things.

**Comment by NeroBurner** [comment]
if you have InfiniSim and in that folder the submodule for InfiniTime, then you just have to open your commandline in the InfiniSim folder and type
```sh
git add InfiniTime
git commit -m "WIP: update InfiniTime to Refactor Notifications PR"
```

The InfiniTime subfolder should be checked out at the commit of your PR with the "Refactor notifications" commit

**Comment by minacode** [comment]
Thank you! I hope I did it right.

> The InfiniTime subfolder should be checked out at the commit of your PR with the "Refactor notifications" commit.

This was the part that confused me. I had to add my fork as remote.

**Comment by NeroBurner** [comment]
step by step, we all had to learn. So never be afraid to ask questions :)

**Comment by minacode** [comment]
Closing this because it is no longer relevant.

**Pull request closed without merging**
