### PR TITLE
littlefs-do binary to work with spi raw file

### PR DESCRIPTION
**Pull request by NeroBurner**
Add helper to modify spi raw file, to make experimenting with it easier.

```sh
$ ./littlefs-do --help
Usage: littlefs-do <command> [options]
Commands:
  -h, --help           show this help message for the selected command and exit
  stat                 show information of specified file or directory
  ls                   list available files in 'spiNorFlash.raw' file
  mkdir                create directory
  rmdir                remove directory
  rm                   remove directory or file
  cp                   copy files into or out of flash file
  settings             list settings from 'settings.h'
```

In the process restructure the CMake file for less duplicate
includes/defines for both executables (`infinisim` and `littlefs-do`).

### CODE REVIEW

**Comment by JF002** [comment]
I've just tested this feature by copying an image from my local fs to the emulated spi flash with https://github.com/InfiniTimeOrg/InfiniTime/pull/1226, and it works!

image

I also find the command 'settings` quite useful:

```
$ ./littlefs-do settings
Calling FS::Init()
running 'settings'
calling Settings::Init()
ClockFace: 0 Digital
Chimes: 0 None
PTSColorTime: Teal
PTSColorBar: Teal
PTSColorBG: Black
AppMenu: 0
SettingsMenu: 0
ClockType: H24
NotificationStatus: 0 ON
ScreenTimeOut: 10000 ms
ShakeThreshold: 150
WakeUpModes: 
- SingleTap:  OFF
- DoubleTap:  OFF
- RaiseWrist: OFF
- Shake:      OFF
Brightness: 2 Medium
StepsGoal: 10000
BleRadioEnabled: true
```

I think there are a few logs that are not needed like `Calling FS::Init()`, `running command 'stat'`,...

**Comment by NeroBurner** [comment]
Thanks for testing the `littlefs-do` binary.

I'll add a `--verbose` flag to make those messages optional, but still available for debugging

**Comment by NeroBurner** [comment]
done, `littlefs-do` is now silent per default, but can be made verbose again with `-v` or `--verbose`

**Comment by JF002** [comment]
> happy you like the settings command, unfortunately it is high maintenance, but I like it as well :)

*Theoretically*, it should be possible to parse the [class Settings](https://github.com/InfiniTimeOrg/InfiniTime/blob/develop/src/components/settings/Settings.h) to discover the fields of the settings at build or run time. Probably not easy to do, but that would reduce the maintenance for this feature :)

**Comment by NeroBurner** [comment]
created a new issue to support a resource file installation command: https://github.com/InfiniTimeOrg/InfiniSim/issues/55

**Pull request merged**
