### PR TITLE
Fixes for PR 2046 (SPI transaction hooks)

### PR DESCRIPTION
**Pull request by mark9064**
Companion for https://github.com/InfiniTimeOrg/InfiniTime/pull/2046

### CODE REVIEW

**Review by JF002 — APPROVED** [review]
I've just merge https://github.com/InfiniTimeOrg/InfiniTime/pull/2046 so I guess we can merge this one too!

**Comment by mark9064** [comment]
I still need to update this for the final version of SPI hooks we went with, don't merge just yet!

**Comment by mark9064** [comment]
Should be ready to go now, builds for me against latest main (when including #142 )

**Comment by NeroBurner** [comment]
Could you update this PR to also update the submodule reference to the latest main state of InfiniTime that works with this PR. Afterwards I'll merge right away. Thanks for the fix!

**Comment by mark9064** [comment]
Rebased on main and updated submodule to InfiniTime main

**Review by NeroBurner — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
