### PR TITLE
fixes for Always On Display and SPI flash ID

### PR DESCRIPTION
**Pull request by ljahn**
This introduces the necessary changes to deal with the changes introduced by the recent always on display and SPI JEDEC ID related commits to InfiniTime

### CODE REVIEW

**Comment by jmlich** [comment]
LGTM. Thanks

**Comment by ljahn** [comment]
The ROUNDED_DIV macro that was missing is already on its way out again with [this](https://github.com/InfiniTimeOrg/InfiniTime/pull/2106) PR to InfiniTIme.

**Comment by mark9064** [comment]
Yeah sorry about that one, the reason why I hadn't pushed a PR here already is because I realised that macro usage was silly. Thanks for preparing this PR :)

**Comment by NeroBurner** [comment]
Updated the InfiniTime submodule to latest `main` commit. Thanks for the fixes

**Pull request merged**
