### PR TITLE
Improve UI for the status window

### PR DESCRIPTION
**Pull request by Brod8362**
image
This PR makes some changes to the status window to make it easier to understand at a glance.

- Add icons to represent what each circle means
- Make the brightness circle sizes different for each brightness level
- Use a bar instead of a bunch of circles for the battery meter
- Rearrange all of the circles to be evenly spaced

Known Issue: you must be running it in the correct directory for it to be able to load the bitmap texture for the background.

Potential for further improvements:
- Display heart rate in this window
- Make it interact-able, or at least show the keys used to manipulate it on screen (easy to do by editing the background bmp)
- Use icons themselves and change the color of them to represent state, instead of a bubble adjacent

The font used for the icons is [FontAwesome 6 Free.](https://fontawesome.com/)

Also, there's a lot of room for improvement as far as the rendering code in general goes. I'm happy to do that, but it's outside of the scope of this PR.

### CODE REVIEW

**Comment by Brod8362** [comment]
Worth noting that the simulator is still usable if it can't load the background, it just won't render it:
image

**Comment by NeroBurner** [comment]
That's looking GREAT. The only thing I'd like to have is to somehow embedd those Bitmaps instead of loading them at runtime

But this looks soooooo good. Love it 😍

**Comment by NeroBurner** [comment]
I think I found something that could work for us

https://blog.gibson.sh/2015/04/13/how-to-integrate-your-sdl2-window-icon-or-any-image-into-your-executable/

**Comment by Brod8362** [comment]
I agree, that would be a good change. A bit busy right now, but I'll try to implement it sometime soon (few days)

**Comment by NeroBurner** [comment]
I've had another shot at it (because I really liked the new look). And I found a solution using a little python. The solution is from https://stackoverflow.com/questions/18422123/sdl-embed-image-inside-program-executable

With this we can convert the `*.bmp` into a `*.c` or `*.h` file and include that in `main.cpp`. Then we just need to read the bmp from memory. I've got a working version locally and will either update this PR or merge your commits squashed into `main`.

Thanks for improving the simulator!

**Comment by NeroBurner** [comment]
Rebased, squashed and added the embedding script. @Brod8362 could you check if this works on your side as well?

**Comment by Brod8362** [comment]
Thanks for the further improvements. I'll take a look at it tonight and let you know - sorry I haven't had time to work on this PR since I originally opened it.

**Comment by Brod8362** [comment]
Just tested, looks good to me.

**Comment by NeroBurner** [comment]
Thanks for the feedback! merging

**Pull request merged**
